const countries: countryData = {
   AD: [
       'Andorra',
       'Andorra la Vella',
       'ca',
       2020,
        'google.ad',
   ],
   AE: [
       'United Arab Emirates',
       'Abu Dhabi',
       'ar',
       2784,
        'google.ae',
   ],
   AF: [
       'Afghanistan',
       'Kabul',
       'ps',
       2004,
        'google.com.af',
   ],
   AG: [
       'Antigua and Barbuda',
       "Saint John's",
       'en',
       2028,
        'google.com.ag',
   ],
   AI: [
       'Anguilla',
       'The Valley',
       'en',
       0,
        null,
   ],
   AL: [
       'Albania',
       'Tirana',
       'sq',
       2008,
        'google.al',
   ],
   AM: [
       'Armenia',
       'Yerevan',
       'hy',
       2051,
        'google.am',
   ],
   AO: [
       'Angola',
       'Luanda',
       'pt',
       2024,
        'google.co.ao',
   ],
   AQ: [
       'Antarctica',
       '',
       '',
       2010,
        null,
   ],
   AR: [
       'Argentina',
       'Buenos Aires',
       'es',
       2032,
        'google.com.ar',
   ],
   AS: [
       'American Samoa',
       'Pago Pago',
       'en',
       2016,
        'google.as',
   ],
   AT: [
       'Austria',
       'Vienna',
       'de',
       2040,
        'google.at',
   ],
   AU: [
       'Australia',
       'Canberra',
       'en',
       2036,
        'google.com.au',
   ],
   AW: [
       'Aruba',
       'Oranjestad',
       'nl',
       0,
        null,
   ],
   AX: [
       'Åland',
       'Mariehamn',
       'sv',
       0,
        null,
   ],
   AZ: [
       'Azerbaijan',
       'Baku',
       'az',
       2031,
        'google.az',
   ],
   BA: [
       'Bosnia and Herzegovina',
       'Sarajevo',
       'bs',
       2070,
        'google.ba',
   ],
   BB: [
       'Barbados',
       'Bridgetown',
       'en',
       2052,
        null,
   ],
   BD: [
       'Bangladesh',
       'Dhaka',
       'bn',
       2050,
        'google.com.bd',
   ],
   BE: [
       'Belgium',
       'Brussels',
       'nl',
       2056,
        'google.be',
   ],
   BF: [
       'Burkina Faso',
       'Ouagadougou',
       'fr',
       2854,
        'google.bf',
   ],
   BG: [
       'Bulgaria',
       'Sofia',
       'bg',
       2100,
        'google.bg',
   ],
   BH: [
       'Bahrain',
       'Manama',
       'ar',
       2048,
        'google.com.bh',
   ],
   BI: [
       'Burundi',
       'Bujumbura',
       'fr',
       2108,
        'google.bi',
   ],
   BJ: [
       'Benin',
       'Porto-Novo',
       'fr',
       2204,
        'google.bj',
   ],
   BL: [
       'Saint Barthélemy',
       'Gustavia',
       'fr',
       2652,
        null,
   ],
   BM: [
       'Bermuda',
       'Hamilton',
       'en',
       0,
        null,
   ],
   BN: [
       'Brunei',
       'Bandar Seri Begawan',
       'ms',
       2096,
        'google.com.bn',
   ],
   BO: [
       'Bolivia',
       'Sucre',
       'es',
       2068,
        'google.com.bo',
   ],
   BQ: [
       'Bonaire',
       'Kralendijk',
       'nl',
       2535,
        null,
   ],
   BR: [
       'Brazil',
       'Brasília',
       'pt',
       2076,
        'google.com.br',
   ],
   BS: [
       'Bahamas',
       'Nassau',
       'en',
       2044,
        'google.bs',
   ],
   BT: [
       'Bhutan',
       'Thimphu',
       'dz',
       2064,
        'google.bt',
   ],
   BV: [
       'Bouvet Island',
       '',
       'no',
       0,
        null,
   ],
   BW: [
       'Botswana',
       'Gaborone',
       'en',
       2072,
        'google.co.bw',
   ],
   BY: [
       'Belarus',
       'Minsk',
       'be',
       2112,
        'google.by',
   ],
   BZ: [
       'Belize',
       'Belmopan',
       'en',
       2084,
        'google.com.bz',
   ],
   CA: [
       'Canada',
       'Ottawa',
       'en',
       2124,
        'google.ca',
   ],
   CC: [
       'Cocos [Keeling] Islands',
       'West Island',
       'en',
       2166,
        null,
   ],
   CD: [
       'Democratic Republic of the Congo',
       'Kinshasa',
       'fr',
       2180,
        'google.cd',
   ],
   CF: [
       'Central African Republic',
       'Bangui',
       'fr',
       2140,
        'google.cf',
   ],
   CG: [
       'Republic of the Congo',
       'Brazzaville',
       'fr',
       2178,
        'google.cg',
   ],
   CH: [
       'Switzerland',
       'Bern',
       'de',
       2756,
        'google.ch',
   ],
   CI: [
       'Ivory Coast',
       'Yamoussoukro',
       'fr',
       2384,
        'google.ci',
   ],
   CK: [
       'Cook Islands',
       'Avarua',
       'en',
       2184,
        'google.co.ck',
   ],
   CL: [
       'Chile',
       'Santiago',
       'es',
       2152,
        'google.cl',
   ],
   CM: [
       'Cameroon',
       'Yaoundé',
       'en',
       2120,
        'google.cm',
   ],
   CN: [
       'China',
       'Beijing',
       'zh',
       2156,
        'google.cn',
   ],
   CO: [
       'Colombia',
       'Bogotá',
       'es',
       2170,
        'google.com.co',
   ],
   CR: [
       'Costa Rica',
       'San José',
       'es',
       2188,
        'google.co.cr',
   ],
   CU: [
       'Cuba',
       'Havana',
       'es',
       0,
        'google.com.cu',
   ],
   CV: [
       'Cape Verde',
       'Praia',
       'pt',
       2132,
        'google.cv',
   ],
   CW: [
       'Curacao',
       'Willemstad',
       'nl',
       2531,
        null,
   ],
   CX: [
       'Christmas Island',
       'Flying Fish Cove',
       'en',
       2162,
        null,
   ],
   CY: [
       'Cyprus',
       'Nicosia',
       'el',
       2196,
        'google.com.cy',
   ],
   CZ: [
       'Czech Republic',
       'Prague',
       'cs',
       2203,
        'google.cz',
   ],
   DE: [
       'Germany',
       'Berlin',
       'de',
       2276,
        'google.de',
   ],
   DJ: [
       'Djibouti',
       'Djibouti',
       'fr',
       2262,
        'google.dj',
   ],
   DK: [
       'Denmark',
       'Copenhagen',
       'da',
       2208,
        'google.dk',
   ],
   DM: [
       'Dominica',
       'Roseau',
       'en',
       2212,
        'google.dm',
   ],
   DO: [
       'Dominican Republic',
       'Santo Domingo',
       'es',
       2214,
        'google.com.do',
   ],
   DZ: [
       'Algeria',
       'Algiers',
       'ar',
       2012,
        'google.dz',
   ],
   EC: [
       'Ecuador',
       'Quito',
       'es',
       2218,
        'google.com.ec',
   ],
   EE: [
       'Estonia',
       'Tallinn',
       'et',
       2233,
        'google.ee',
   ],
   EG: [
       'Egypt',
       'Cairo',
       'ar',
       2818,
        'google.com.eg',
   ],
   EH: [
       'Western Sahara',
       'El Aaiún',
       'es',
       0,
        null,
   ],
   ER: [
       'Eritrea',
       'Asmara',
       'ti',
       2232,
        null,
   ],
   ES: [
       'Spain',
       'Madrid',
       'es',
       2724,
        'google.es',
   ],
   ET: [
       'Ethiopia',
       'Addis Ababa',
       'am',
       2231,
        'google.com.et',
   ],
   FI: [
       'Finland',
       'Helsinki',
       'fi',
       2246,
        'google.fi',
   ],
   FJ: [
       'Fiji',
       'Suva',
       'en',
       2242,
        'google.com.fj',
   ],
   FK: [
       'Falkland Islands',
       'Stanley',
       'en',
       0,
        null,
   ],
   FM: [
       'Micronesia',
       'Palikir',
       'en',
       2583,
        'google.fm',
   ],
   FO: [
       'Faroe Islands',
       'Tórshavn',
       'fo',
       0,
        null,
   ],
   FR: [
       'France',
       'Paris',
       'fr',
       2250,
        'google.fr',
   ],
   GA: [
       'Gabon',
       'Libreville',
       'fr',
       2266,
        'google.ga',
   ],
   GB: [
       'United Kingdom',
       'London',
       'en',
       2826,
        'google.co.uk',
   ],
   GD: [
       'Grenada',
       "St. George's",
       'en',
       2308,
        null,
   ],
   GE: [
       'Georgia',
       'Tbilisi',
       'ka',
       2268,
        'google.ge',
   ],
   GF: [
       'French Guiana',
       'Cayenne',
       'fr',
       0,
        null,
   ],
   GG: [
       'Guernsey',
       'St. Peter Port',
       'en',
       2831,
        'google.gg',
   ],
   GH: [
       'Ghana',
       'Accra',
       'en',
       2288,
        'google.com.gh',
   ],
   GI: [
       'Gibraltar',
       'Gibraltar',
       'en',
       0,
        'google.com.gi',
   ],
   GL: [
       'Greenland',
       'Nuuk',
       'kl',
       0,
        'google.gl',
   ],
   GM: [
       'Gambia',
       'Banjul',
       'en',
       2270,
        'google.gm',
   ],
   GN: [
       'Guinea',
       'Conakry',
       'fr',
       2324,
        null,
   ],
   GP: [
       'Guadeloupe',
       'Basse-Terre',
       'fr',
       0,
        'google.gp',
   ],
   GQ: [
       'Equatorial Guinea',
       'Malabo',
       'es',
       2226,
        null,
   ],
   GR: [
       'Greece',
       'Athens',
       'el',
       2300,
        'google.gr',
   ],
   GS: [
       'South Georgia and the South Sandwich Islands',
       'King Edward Point',
       'en',
       2239,
        null,
   ],
   GT: [
       'Guatemala',
       'Guatemala City',
       'es',
       2320,
        'google.com.gt',
   ],
   GU: [
       'Guam',
       'Hagåtña',
       'en',
       2316,
        null,
   ],
   GW: [
       'Guinea-Bissau',
       'Bissau',
       'pt',
       2624,
        null,
   ],
   GY: [
       'Guyana',
       'Georgetown',
       'en',
       2328,
        'google.gy',
   ],
   HK: [
       'Hong Kong',
       'City of Victoria',
       'zh',
       0,
        'google.com.hk',
   ],
   HM: [
       'Heard Island and McDonald Islands',
       '',
       'en',
       2334,
        null,
   ],
   HN: [
       'Honduras',
       'Tegucigalpa',
       'es',
       2340,
        'google.hn',
   ],
   HR: [
       'Croatia',
       'Zagreb',
       'hr',
       2191,
        'google.hr',
   ],
   HT: [
       'Haiti',
       'Port-au-Prince',
       'fr',
       2332,
        'google.ht',
   ],
   HU: [
       'Hungary',
       'Budapest',
       'hu',
       2348,
        'google.hu',
   ],
   ID: [
       'Indonesia',
       'Jakarta',
       'id',
       2360,
        'google.co.id',
   ],
   IE: [
       'Ireland',
       'Dublin',
       'ga',
       2372,
        'google.ie',
   ],
   IL: [
       'Israel',
       'Jerusalem',
       'he',
       2376,
        'google.co.il',
   ],
   IM: [
       'Isle of Man',
       'Douglas',
       'en',
       2833,
        'google.im',
   ],
   IN: [
       'India',
       'New Delhi',
       'hi',
       2356,
        'google.co.in',
   ],
   IO: [
       'British Indian Ocean Territory',
       'Diego Garcia',
       'en',
       0,
        null,
   ],
   IQ: [
       'Iraq',
       'Baghdad',
       'ar',
       2368,
        'google.iq',
   ],
   IR: [
       'Iran',
       'Tehran',
       'fa',
       0,
        null,
   ],
   IS: [
       'Iceland',
       'Reykjavik',
       'is',
       2352,
        'google.is',
   ],
   IT: [
       'Italy',
       'Rome',
       'it',
       2380,
        'google.it',
   ],
   JE: [
       'Jersey',
       'Saint Helier',
       'en',
       2832,
        'google.je',
   ],
   JM: [
       'Jamaica',
       'Kingston',
       'en',
       2388,
        'google.com.jm',
   ],
   JO: [
       'Jordan',
       'Amman',
       'ar',
       2400,
        'google.jo',
   ],
   JP: [
       'Japan',
       'Tokyo',
       'ja',
       2392,
        'google.co.jp',
   ],
   KE: [
       'Kenya',
       'Nairobi',
       'en',
       2404,
        'google.co.ke',
   ],
   KG: [
       'Kyrgyzstan',
       'Bishkek',
       'ky',
       2417,
        'google.kg',
   ],
   KH: [
       'Cambodia',
       'Phnom Penh',
       'km',
       2116,
        'google.com.kh',
   ],
   KI: [
       'Kiribati',
       'South Tarawa',
       'en',
       2296,
        'google.ki',
   ],
   KM: [
       'Comoros',
       'Moroni',
       'ar',
       2174,
        null,
   ],
   KN: [
       'Saint Kitts and Nevis',
       'Basseterre',
       'en',
       2659,
        null,
   ],
   KP: [
       'North Korea',
       'Pyongyang',
       'ko',
       0,
        null,
   ],
   KR: [
       'South Korea',
       'Seoul',
       'ko',
       2410,
        'google.co.kr',
   ],
   KW: [
       'Kuwait',
       'Kuwait City',
       'ar',
       2414,
        'google.com.kw',
   ],
   KY: [
       'Cayman Islands',
       'George Town',
       'en',
       0,
        null,
   ],
   KZ: [
       'Kazakhstan',
       'Astana',
       'kk',
       2398,
        'google.kz',
   ],
   LA: [
       'Laos',
       'Vientiane',
       'lo',
       2418,
        'google.la',
   ],
   LB: [
       'Lebanon',
       'Beirut',
       'ar',
       2422,
        'google.com.lb',
   ],
   LC: [
       'Saint Lucia',
       'Castries',
       'en',
       2662,
        null,
   ],
   LI: [
       'Liechtenstein',
       'Vaduz',
       'de',
       2438,
        'google.li',
   ],
   LK: [
       'Sri Lanka',
       'Colombo',
       'si',
       2144,
        'google.lk',
   ],
   LR: [
       'Liberia',
       'Monrovia',
       'en',
       2430,
        null,
   ],
   LS: [
       'Lesotho',
       'Maseru',
       'en',
       2426,
        'google.co.ls',
   ],
   LT: [
       'Lithuania',
       'Vilnius',
       'lt',
       2440,
        'google.lt',
   ],
   LU: [
       'Luxembourg',
       'Luxembourg',
       'fr',
       2442,
        'google.lu',
   ],
   LV: [
       'Latvia',
       'Riga',
       'lv',
       2428,
        'google.lv',
   ],
   LY: [
       'Libya',
       'Tripoli',
       'ar',
       2434,
        'google.com.ly',
   ],
   MA: [
       'Morocco',
       'Rabat',
       'ar',
       2504,
        'google.co.ma',
   ],
   MC: [
       'Monaco',
       'Monaco',
       'fr',
       2492,
        null,
   ],
   MD: [
       'Moldova',
       'Chișinău',
       'ro',
       2498,
        'google.md',
   ],
   ME: [
       'Montenegro',
       'Podgorica',
       'sr',
       2499,
        'google.me',
   ],
   MF: [
       'Saint Martin',
       'Marigot',
       'en',
       2663,
        null,
   ],
   MG: [
       'Madagascar',
       'Antananarivo',
       'fr',
       2450,
        'google.mg',
   ],
   MH: [
       'Marshall Islands',
       'Majuro',
       'en',
       2584,
        null,
   ],
   MK: [
       'North Macedonia',
       'Skopje',
       'mk',
       2807,
        'google.mk',
   ],
   ML: [
       'Mali',
       'Bamako',
       'fr',
       2466,
        'google.ml',
   ],
   MM: [
       'Myanmar [Burma]',
       'Naypyidaw',
       'my',
       2104,
        'google.com.mm',
   ],
   MN: [
       'Mongolia',
       'Ulan Bator',
       'mn',
       2496,
        'google.mn',
   ],
   MO: [
       'Macao',
       'Macao',
       'zh',
       0,
        null,
   ],
   MP: [
       'Northern Mariana Islands',
       'Saipan',
       'en',
       2580,
        null,
   ],
   MQ: [
       'Martinique',
       'Fort-de-France',
       'fr',
       0,
        null,
   ],
   MR: [
       'Mauritania',
       'Nouakchott',
       'ar',
       2478,
        null,
   ],
   MS: [
       'Montserrat',
       'Plymouth',
       'en',
       0,
        'google.ms',
   ],
   MT: [
       'Malta',
       'Valletta',
       'mt',
       2470,
        'google.com.mt',
   ],
   MU: [
       'Mauritius',
       'Port Louis',
       'en',
       2480,
        'google.mu',
   ],
   MV: [
       'Maldives',
       'Malé',
       'dv',
       2462,
        'google.mv',
   ],
   MW: [
       'Malawi',
       'Lilongwe',
       'en',
       2454,
        'google.mw',
   ],
   MX: [
       'Mexico',
       'Mexico City',
       'es',
       2484,
        'google.com.mx',
   ],
   MY: [
       'Malaysia',
       'Kuala Lumpur',
       'ms',
       2458,
        'google.com.my',
   ],
   MZ: [
       'Mozambique',
       'Maputo',
       'pt',
       2508,
        'google.co.mz',
   ],
   NA: [
       'Namibia',
       'Windhoek',
       'en',
       2516,
        'google.com.na',
   ],
   NC: [
       'New Caledonia',
       'Nouméa',
       'fr',
       2540,
        null,
   ],
   NE: [
       'Niger',
       'Niamey',
       'fr',
       2562,
        'google.ne',
   ],
   NF: [
       'Norfolk Island',
       'Kingston',
       'en',
       2574,
        null,
   ],
   NG: [
       'Nigeria',
       'Abuja',
       'en',
       2566,
        'google.com.ng',
   ],
   NI: [
       'Nicaragua',
       'Managua',
       'es',
       2558,
        'google.com.ni',
   ],
   NL: [
       'Netherlands',
       'Amsterdam',
       'nl',
       2528,
        'google.nl',
   ],
   NO: [
       'Norway',
       'Oslo',
       'no',
       2578,
        'google.no',
   ],
   NP: [
       'Nepal',
       'Kathmandu',
       'ne',
       2524,
        'google.com.np',
   ],
   NR: [
       'Nauru',
       'Yaren',
       'en',
       2520,
        'google.nr',
   ],
   NU: [
       'Niue',
       'Alofi',
       'en',
       2570,
        'google.nu',
   ],
   NZ: [
       'New Zealand',
       'Wellington',
       'en',
       2554,
        'google.co.nz',
   ],
   OM: [
       'Oman',
       'Muscat',
       'ar',
       2512,
        'google.com.om',
   ],
   PA: [
       'Panama',
       'Panama City',
       'es',
       2591,
        'google.com.pa',
   ],
   PE: [
       'Peru',
       'Lima',
       'es',
       2604,
        'google.com.pe',
   ],
   PF: [
       'French Polynesia',
       'Papeetē',
       'fr',
       2258,
        null,
   ],
   PG: [
       'Papua New Guinea',
       'Port Moresby',
       'en',
       2598,
        'google.com.pg',
   ],
   PH: [
       'Philippines',
       'Manila',
       'en',
       2608,
        'google.com.ph',
   ],
   PK: [
       'Pakistan',
       'Islamabad',
       'en',
       2586,
        'google.com.pk',
   ],
   PL: [
       'Poland',
       'Warsaw',
       'pl',
       2616,
        'google.pl',
   ],
   PM: [
       'Saint Pierre and Miquelon',
       'Saint-Pierre',
       'fr',
       2666,
        null,
   ],
   PN: [
       'Pitcairn Islands',
       'Adamstown',
       'en',
       2612,
        'google.pn',
   ],
   PR: [
       'Puerto Rico',
       'San Juan',
       'es',
       0,
        'google.com.pr',
   ],
   PS: [
       'Palestine',
       'Ramallah',
       'ar',
       0,
        'google.ps',
   ],
   PT: [
       'Portugal',
       'Lisbon',
       'pt',
       2620,
        'google.pt',
   ],
   PW: [
       'Palau',
       'Ngerulmud',
       'en',
       2585,
        null,
   ],
   PY: [
       'Paraguay',
       'Asunción',
       'es',
       2600,
        'google.com.py',
   ],
   QA: [
       'Qatar',
       'Doha',
       'ar',
       2634,
        'google.com.qa',
   ],
   RE: [
       'Réunion',
       'Saint-Denis',
       'fr',
       0,
        null,
   ],
   RO: [
       'Romania',
       'Bucharest',
       'ro',
       2642,
        'google.ro',
   ],
   RS: [
       'Serbia',
       'Belgrade',
       'sr',
       2688,
        'google.rs',
   ],
   RU: [
       'Russia',
       'Moscow',
       'ru',
       2643,
        'google.ru',
   ],
   RW: [
       'Rwanda',
       'Kigali',
       'rw',
       2646,
        'google.rw',
   ],
   SA: [
       'Saudi Arabia',
       'Riyadh',
       'ar',
       2682,
        'google.com.sa',
   ],
   SB: [
       'Solomon Islands',
       'Honiara',
       'en',
       2090,
        'google.com.sb',
   ],
   SC: [
       'Seychelles',
       'Victoria',
       'fr',
       2690,
        'google.sc',
   ],
   SD: [
       'Sudan',
       'Khartoum',
       'ar',
       2736,
        null,
   ],
   SE: [
       'Sweden',
       'Stockholm',
       'sv',
       2752,
        'google.se',
   ],
   SG: [
       'Singapore',
       'Singapore',
       'en',
       2702,
        'google.com.sg',
   ],
   SH: [
       'Saint Helena',
       'Jamestown',
       'en',
       2654,
        'google.sh',
   ],
   SI: [
       'Slovenia',
       'Ljubljana',
       'sl',
       2705,
        'google.si',
   ],
   SJ: [
       'Svalbard and Jan Mayen',
       'Longyearbyen',
       'no',
       0,
        null,
   ],
   SK: [
       'Slovakia',
       'Bratislava',
       'sk',
       2703,
        'google.sk',
   ],
   SL: [
       'Sierra Leone',
       'Freetown',
       'en',
       2694,
        'google.com.sl',
   ],
   SM: [
       'San Marino',
       'City of San Marino',
       'it',
       2674,
        'google.sm',
   ],
   SN: [
       'Senegal',
       'Dakar',
       'fr',
       2686,
        'google.sn',
   ],
   SO: [
       'Somalia',
       'Mogadishu',
       'so',
       2706,
        'google.so',
   ],
   SR: [
       'Suriname',
       'Paramaribo',
       'nl',
       2740,
        'google.sr',
   ],
   SS: [
       'South Sudan',
       'Juba',
       'en',
       2728,
        null,
   ],
   ST: [
       'São Tomé and Príncipe',
       'São Tomé',
       'pt',
       2678,
        'google.st',
   ],
   SV: [
       'El Salvador',
       'San Salvador',
       'es',
       2222,
        'google.com.sv',
   ],
   SX: [
       'Sint Maarten',
       'Philipsburg',
       'nl',
       2534,
        null,
   ],
   SY: [
       'Syria',
       'Damascus',
       'ar',
       0,
        null,
   ],
   SZ: [
       'Swaziland',
       'Lobamba',
       'en',
       2748,
        null,
   ],
   TC: [
       'Turks and Caicos Islands',
       'Cockburn Town',
       'en',
       0,
        null,
   ],
   TD: [
       'Chad',
       "N'Djamena",
       'fr',
       2148,
        'google.td',
   ],
   TF: [
       'French Southern Territories',
       'Port-aux-Français',
       'fr',
       2260,
        null,
   ],
   TG: [
       'Togo',
       'Lomé',
       'fr',
       2768,
        'google.tg',
   ],
   TH: [
       'Thailand',
       'Bangkok',
       'th',
       2764,
        'google.co.th',
   ],
   TJ: [
       'Tajikistan',
       'Dushanbe',
       'tg',
       2762,
        'google.com.tj',
   ],
   TK: [
       'Tokelau',
       'Fakaofo',
       'en',
       2772,
        null,
   ],
   TL: [
       'East Timor',
       'Dili',
       'pt',
       2626,
        'google.tl',
   ],
   TM: [
       'Turkmenistan',
       'Ashgabat',
       'tk',
       2795,
        'google.tm',
   ],
   TN: [
       'Tunisia',
       'Tunis',
       'ar',
       2788,
        'google.tn',
   ],
   TO: [
       'Tonga',
       "Nuku'alofa",
       'en',
       2776,
        'google.to',
   ],
   TR: [
       'Turkey',
       'Ankara',
       'tr',
       2792,
        'google.com.tr',
   ],
   TT: [
       'Trinidad and Tobago',
       'Port of Spain',
       'en',
       2780,
        'google.tt',
   ],
   TV: [
       'Tuvalu',
       'Funafuti',
       'en',
       2798,
        null,
   ],
   TW: [
       'Taiwan',
       'Taipei',
       'zh',
       0,
        'google.com.tw',
   ],
   TZ: [
       'Tanzania',
       'Dodoma',
       'sw',
       2834,
        'google.co.tz',
   ],
   UA: [
       'Ukraine',
       'Kyiv',
       'uk',
       2804,
        'google.com.ua',
   ],
   UG: [
       'Uganda',
       'Kampala',
       'en',
       2800,
        'google.co.ug',
   ],
   UM: [
       'U.S. Minor Outlying Islands',
       '',
       'en',
       2581,
        null,
   ],
   US: [
       'United States',
       'New York',
       'en',
       2840,
        'google.com',
   ],
   UY: [
       'Uruguay',
       'Montevideo',
       'es',
       2858,
        'google.com.uy',
   ],
   UZ: [
       'Uzbekistan',
       'Tashkent',
       'uz',
       2860,
        'google.co.uz',
   ],
   VA: [
       'Vatican City',
       'Vatican City',
       'it',
       2336,
        null,
   ],
   VC: [
       'Saint Vincent and the Grenadines',
       'Kingstown',
       'en',
       2670,
        'google.com.vc',
   ],
   VE: [
       'Venezuela',
       'Caracas',
       'es',
       2862,
        'google.co.ve',
   ],
   VG: [
       'British Virgin Islands',
       'Road Town',
       'en',
       0,
        'google.vg',
   ],
   VI: [
       'U.S. Virgin Islands',
       'Charlotte Amalie',
       'en',
       0,
        'google.co.vi',
   ],
   VN: [
       'Vietnam',
       'Hanoi',
       'vi',
       2704,
        'google.com.vn',
   ],
   VU: [
       'Vanuatu',
       'Port Vila',
       'bi',
       2548,
        'google.vu',
   ],
   WF: [
       'Wallis and Futuna',
       'Mata-Utu',
       'fr',
       2876,
        null,
   ],
   WS: [
       'Samoa',
       'Apia',
       'sm',
       2882,
        'google.ws',
   ],
   XK: [
       'Kosovo',
       'Pristina',
       'sq',
       0,
        null,
   ],
   YE: [
       'Yemen',
       "Sana'a",
       'ar',
       2887,
        null,
   ],
   YT: [
       'Mayotte',
       'Mamoudzou',
       'fr',
       0,
        null,
   ],
   ZA: [
       'South Africa',
       'Pretoria',
       'af',
       2710,
        'google.co.za',
   ],
   ZM: [
       'Zambia',
       'Lusaka',
       'en',
       2894,
        'google.co.zm',
   ],
   ZW: [
       'Zimbabwe',
       'Harare',
       'en',
       2716,
        'google.co.zw',
   ],
   ZZ: [
       'Unknown',
       'Unknown',
       'en',
       0,
        null,
   ],
};

export const countryAlphaTwoCodes: countryCodeData = {
   AFG: 'AF',
   ALA: 'AX',
   ALB: 'AL',
   DZA: 'DZ',
   ASM: 'AS',
   AND: 'AD',
   AGO: 'AO',
   AIA: 'AI',
   ATA: 'AQ',
   ATG: 'AG',
   ARG: 'AR',
   ARM: 'AM',
   ABW: 'AW',
   AUS: 'AU',
   AUT: 'AT',
   AZE: 'AZ',
   BHS: 'BS',
   BHR: 'BH',
   BGD: 'BD',
   BRB: 'BB',
   BLR: 'BY',
   BEL: 'BE',
   BLZ: 'BZ',
   BEN: 'BJ',
   BMU: 'BM',
   BTN: 'BT',
   BOL: 'BO',
   BES: 'BQ',
   BIH: 'BA',
   BWA: 'BW',
   BVT: 'BV',
   BRA: 'BR',
   IOT: 'IO',
   BRN: 'BN',
   BGR: 'BG',
   BFA: 'BF',
   BDI: 'BI',
   CPV: 'CV',
   KHM: 'KH',
   CMR: 'CM',
   CAN: 'CA',
   CYM: 'KY',
   CAF: 'CF',
   TCD: 'TD',
   CHL: 'CL',
   CHN: 'CN',
   CXR: 'CX',
   CCK: 'CC',
   COL: 'CO',
   COM: 'KM',
   COG: 'CG',
   COD: 'CD',
   COK: 'CK',
   CRI: 'CR',
   CIV: 'CI',
   HRV: 'HR',
   CUB: 'CU',
   CUW: 'CW',
   CYP: 'CY',
   CZE: 'CZ',
   DNK: 'DK',
   DJI: 'DJ',
   DMA: 'DM',
   DOM: 'DO',
   ECU: 'EC',
   EGY: 'EG',
   SLV: 'SV',
   GNQ: 'GQ',
   ERI: 'ER',
   EST: 'EE',
   SWZ: 'SZ',
   ETH: 'ET',
   FLK: 'FK',
   FRO: 'FO',
   FJI: 'FJ',
   FIN: 'FI',
   FRA: 'FR',
   GUF: 'GF',
   PYF: 'PF',
   ATF: 'TF',
   GAB: 'GA',
   GMB: 'GM',
   GEO: 'GE',
   DEU: 'DE',
   GHA: 'GH',
   GIB: 'GI',
   GRC: 'GR',
   GRL: 'GL',
   GRD: 'GD',
   GLP: 'GP',
   GUM: 'GU',
   GTM: 'GT',
   GGY: 'GG',
   GIN: 'GN',
   GNB: 'GW',
   GUY: 'GY',
   HTI: 'HT',
   HMD: 'HM',
   VAT: 'VA',
   HND: 'HN',
   HKG: 'HK',
   HUN: 'HU',
   ISL: 'IS',
   IND: 'IN',
   IDN: 'ID',
   IRN: 'IR',
   IRQ: 'IQ',
   IRL: 'IE',
   IMN: 'IM',
   ISR: 'IL',
   ITA: 'IT',
   JAM: 'JM',
   JPN: 'JP',
   JEY: 'JE',
   JOR: 'JO',
   KAZ: 'KZ',
   KEN: 'KE',
   KIR: 'KI',
   PRK: 'KP',
   KOR: 'KR',
   KWT: 'KW',
   KGZ: 'KG',
   LAO: 'LA',
   LVA: 'LV',
   LBN: 'LB',
   LSO: 'LS',
   LBR: 'LR',
   LBY: 'LY',
   LIE: 'LI',
   LTU: 'LT',
   LUX: 'LU',
   MAC: 'MO',
   MDG: 'MG',
   MWI: 'MW',
   MYS: 'MY',
   MDV: 'MV',
   MLI: 'ML',
   MLT: 'MT',
   MHL: 'MH',
   MTQ: 'MQ',
   MRT: 'MR',
   MUS: 'MU',
   MYT: 'YT',
   MEX: 'MX',
   FSM: 'FM',
   MDA: 'MD',
   MCO: 'MC',
   MNG: 'MN',
   MNE: 'ME',
   MSR: 'MS',
   MAR: 'MA',
   MOZ: 'MZ',
   MMR: 'MM',
   NAM: 'NA',
   NRU: 'NR',
   NPL: 'NP',
   NLD: 'NL',
   NCL: 'NC',
   NZL: 'NZ',
   NIC: 'NI',
   NER: 'NE',
   NGA: 'NG',
   NIU: 'NU',
   NFK: 'NF',
   MKD: 'MK',
   MNP: 'MP',
   NOR: 'NO',
   OMN: 'OM',
   PAK: 'PK',
   PLW: 'PW',
   PSE: 'PS',
   PAN: 'PA',
   PNG: 'PG',
   PRY: 'PY',
   PER: 'PE',
   PHL: 'PH',
   PCN: 'PN',
   POL: 'PL',
   PRT: 'PT',
   PRI: 'PR',
   QAT: 'QA',
   REU: 'RE',
   ROU: 'RO',
   RUS: 'RU',
   RWA: 'RW',
   BLM: 'BL',
   SHN: 'SH',
   KNA: 'KN',
   LCA: 'LC',
   MAF: 'MF',
   SPM: 'PM',
   VCT: 'VC',
   WSM: 'WS',
   SMR: 'SM',
   STP: 'ST',
   SAU: 'SA',
   SEN: 'SN',
   SRB: 'RS',
   SYC: 'SC',
   SLE: 'SL',
   SGP: 'SG',
   SXM: 'SX',
   SVK: 'SK',
   SVN: 'SI',
   SLB: 'SB',
   SOM: 'SO',
   ZAF: 'ZA',
   SGS: 'GS',
   SSD: 'SS',
   ESP: 'ES',
   LKA: 'LK',
   SDN: 'SD',
   SUR: 'SR',
   SJM: 'SJ',
   SWE: 'SE',
   CHE: 'CH',
   SYR: 'SY',
   TWN: 'TW',
   TJK: 'TJ',
   TZA: 'TZ',
   THA: 'TH',
   TLS: 'TL',
   TGO: 'TG',
   TKL: 'TK',
   TON: 'TO',
   TTO: 'TT',
   TUN: 'TN',
   TUR: 'TR',
   TKM: 'TM',
   TCA: 'TC',
   TUV: 'TV',
   UGA: 'UG',
   UKR: 'UA',
   ARE: 'AE',
   GBR: 'GB',
   USA: 'US',
   UMI: 'UM',
   URY: 'UY',
   UZB: 'UZ',
   VUT: 'VU',
   VEN: 'VE',
   VNM: 'VN',
   VGB: 'VG',
   VIR: 'VI',
   WLF: 'WF',
   ESH: 'EH',
   YEM: 'YE',
   ZMB: 'ZM',
   ZWE: 'ZW',
   ZZZ: 'ZZ',
};

export const adwordsLanguages: Record<number, string> = {
   1000: 'English',
   1001: 'German',
   1002: 'French',
   1003: 'Spanish',
   1004: 'Italian',
   1005: 'Japanese',
   1009: 'Danish',
   1010: 'Dutch',
   1011: 'Finnish',
   1012: 'Korean',
   1013: 'Norwegian',
   1014: 'Portuguese',
   1015: 'Swedish',
   1017: 'Chinese (simplified)',
   1018: 'Chinese (traditional)',
   1019: 'Arabic',
   1020: 'Bulgarian',
   1021: 'Czech',
   1022: 'Greek',
   1023: 'Hindi',
   1024: 'Hungarian',
   1025: 'Indonesian',
   1026: 'Icelandic',
   1027: 'Hebrew',
   1028: 'Latvian',
   1029: 'Lithuanian',
   1030: 'Polish',
   1031: 'Russian',
   1032: 'Romanian',
   1033: 'Slovak',
   1034: 'Slovenian',
   1035: 'Serbian',
   1036: 'Ukrainian',
   1037: 'Turkish',
   1038: 'Catalan',
   1039: 'Croatian',
   1040: 'Vietnamese',
   1041: 'Urdu',
   1042: 'Filipino',
   1043: 'Estonian',
   1044: 'Thai',
   1056: 'Bengali',
   1064: 'Persian',
   1072: 'Gujarati',
   1086: 'Kannada',
   1098: 'Malayalam',
   1101: 'Marathi',
   1102: 'Malay',
   1110: 'Punjabi',
   1130: 'Tamil',
   1131: 'Telugu',
};

export const getCountryCodeFromAlphaThree = (AlphaThreeCode:string): string => countryAlphaTwoCodes[AlphaThreeCode];

/**
 * Gets the Google domain for a given country code
 * @param countryCode - The ISO 2-letter country code
 * @returns The Google domain for the country, or 'google.com' as fallback
 */
export const getGoogleDomain = (countryCode: string): string => {
   const country = countries[countryCode.toUpperCase()];
   return country?.[4] ?? 'google.com';
};

export default countries;
